version: "1.0"

services:
  api_elias:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
    depends_on:
      - database  # Corrected indentation and added a space between the hyphen and "database"

  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"  # Expose the PostgreSQL container's port
    volumes:
      - postgres_data:/var/lib/postgres/data/

volumes:
  postgres_data:
    driver: local

